services:
  hanamikoji_postgres:
    container_name: hanamikoji_postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - "5432:5432"
    volumes:
      - hanamikoji_volume:/var/lib/postgresql/data
    networks:
      - hanamikoji_network
    restart: always
volumes:
  hanamikoji_volume:
networks:
  hanamikoji_network:
    driver: bridge
