services:
  hanamikoji_postgres:
    container_name: hanamikoji_postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - hanamikoji_volume:/var/lib/postgresql/data
    networks:
      - hanamikoji_network
    restart: always
volumes:
  hanamikoji_volume:
networks:
  hanamikoji_network:
    driver: bridge
